apiVersion: apps/v1
kind: Deployment
metadata:
  name: yt-reverse-playlist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yt-reverse-playlist
  template:
    metadata:
      labels:
        app: yt-reverse-playlist
    spec:
      terminationGracePeriodSeconds: 165
      containers:
        - name: backend
          image: registry.digitalocean.com/lastfirst/backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: YT_API_KEY
              valueFrom:
                secretKeyRef:
                  name: yt-api-key
                  key: YT_API_KEY
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20
